name: Run TypeScript Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-ts-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install  # or yarn install, depending on your setup

      - name: Run TypeScript script
        run: npm run scrape # Replace with the path to your TypeScript file
